# Generated by Django 4.2.26 on 2026-10-09 16:15

import uuid

import django.core.serializers.json
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
from django.db import migrations, models

import nautobot_firewall_models.utils


def copy_zone_fks_to_m2m(apps, schema_editor):
    """Carry each rule's single source/destination Zone over to the new many-to-many fields."""
    for model_name in ("PolicyRule", "NATPolicyRule"):
        model = apps.get_model("nautobot_firewall_models", model_name)
        for side in ("source", "destination"):
            through = getattr(model, f"{side}_zones").through
            rule_fk = f"{model_name.lower()}_id"
            rows = model.objects.filter(**{f"{side}_zone__isnull": False}).values_list("pk", f"{side}_zone_id")
            through.objects.bulk_create(
                [through(**{rule_fk: rule_pk, "zone_id": zone_pk}) for rule_pk, zone_pk in rows]
            )


def copy_zone_m2m_to_fks(apps, schema_editor):
    """Reverse: keep the first Zone on each side. Zone groups and any extra Zones are dropped."""
    for model_name in ("PolicyRule", "NATPolicyRule"):
        model = apps.get_model("nautobot_firewall_models", model_name)
        for rule in model.objects.all():
            rule.source_zone = rule.source_zones.order_by("name").first()
            rule.destination_zone = rule.destination_zones.order_by("name").first()
            rule.save(update_fields=["source_zone", "destination_zone"])


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0132_approval_workflow_seed_data"),
        ("nautobot_firewall_models", "0024_delete_capircapolicy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyrule",
            name="source_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nautobot_firewall_models.zone",
            ),
        ),
        migrations.AlterField(
            model_name="policyrule",
            name="destination_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nautobot_firewall_models.zone",
            ),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="source_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nautobot_firewall_models.zone",
            ),
        ),
        migrations.AlterField(
            model_name="natpolicyrule",
            name="destination_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="nautobot_firewall_models.zone",
            ),
        ),
        migrations.AddField(
            model_name="natpolicyrule",
            name="destination_zones",
            field=models.ManyToManyField(
                blank=True, related_name="destination_nat_policy_rules", to="nautobot_firewall_models.zone"
            ),
        ),
        migrations.AddField(
            model_name="natpolicyrule",
            name="source_zones",
            field=models.ManyToManyField(
                blank=True, related_name="source_nat_policy_rules", to="nautobot_firewall_models.zone"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="destination_zones",
            field=models.ManyToManyField(
                blank=True, related_name="destination_policy_rules", to="nautobot_firewall_models.zone"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_zones",
            field=models.ManyToManyField(
                blank=True, related_name="source_policy_rules", to="nautobot_firewall_models.zone"
            ),
        ),
        migrations.CreateModel(
            name="ZoneGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("description", models.CharField(blank=True, max_length=1024)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        default=nautobot_firewall_models.utils.get_default_status,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to="extras.status",
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
                (
                    "zones",
                    models.ManyToManyField(blank=True, related_name="zone_groups", to="nautobot_firewall_models.zone"),
                ),
            ],
            options={
                "verbose_name_plural": "Zone Groups",
                "ordering": ["name"],
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="natpolicyrule",
            name="destination_zone_groups",
            field=models.ManyToManyField(
                blank=True, related_name="destination_nat_policy_rules", to="nautobot_firewall_models.zonegroup"
            ),
        ),
        migrations.AddField(
            model_name="natpolicyrule",
            name="source_zone_groups",
            field=models.ManyToManyField(
                blank=True, related_name="source_nat_policy_rules", to="nautobot_firewall_models.zonegroup"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="destination_zone_groups",
            field=models.ManyToManyField(
                blank=True, related_name="destination_policy_rules", to="nautobot_firewall_models.zonegroup"
            ),
        ),
        migrations.AddField(
            model_name="policyrule",
            name="source_zone_groups",
            field=models.ManyToManyField(
                blank=True, related_name="source_policy_rules", to="nautobot_firewall_models.zonegroup"
            ),
        ),
        migrations.RunPython(copy_zone_fks_to_m2m, copy_zone_m2m_to_fks),
        migrations.RemoveField(
            model_name="natpolicyrule",
            name="destination_zone",
        ),
        migrations.RemoveField(
            model_name="natpolicyrule",
            name="source_zone",
        ),
        migrations.RemoveField(
            model_name="policyrule",
            name="destination_zone",
        ),
        migrations.RemoveField(
            model_name="policyrule",
            name="source_zone",
        ),
    ]
